-- math functions
SELECT SUM(COST) AS "SUM_OF_COST" FROM PETRESCUE;
SELECT MAX(QUANTITY) FROM PETRESCUE;
SELECT MIN(QUANTITY) FROM PETRESCUE;
SELECT AVG(COST) FROM PETRESCUE;

--round functions, extra parameter tells significant figs
SELECT ROUND(COST) FROM PETRESCUE;
SELECT ROUND(COST, 0) FROM PETRESCUE;
SELECT ROUND(COST, 2) FROM PETRESCUE;

--string functions
SELECT LENGTH(ANIMAL) FROM PETRESCUE;
SELECT UCASE(ANIMAL) FROM PETRESCUE;
SELECT LCASE(ANIMAL) FROM PETRESCUE;

--date funcions
SELECT DAY(RESCUEDATE) FROM PETRESCUE;
SELECT MONTH(RESCUEDATE) FROM PETRESCUE;
SELECT YEAR(RESCUEDATE) FROM PETRESCUE;

--pet should see vet within 3days of rescue, how to find that?
SELECT DATE_ADD(RESCUEDATE, INTERVAL 3 DAY) FROM petrescue;
-- if condition was to see vet within 2 months
SELECT DATE_ADD(RESCUEDATE, INTERVAL 2 MONTH) FROM PETRESCUE;

--these tell date after the mentioned date, what if we want the before date (like 3 days before rescue)
SELECT DATE_SUB(RESCUEDATE, INTERVAL 3 DAY) FROM PETRESCUE;
--this tells the time since animal have been rescued
SELECT FROM_DAYS(DATEDIFF(CURRENT_DATE, RESCUEDATE)) FROM PETRESCUE